### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by Lucas-Pavao** [Lucas-Pavao/GCMS-Lucas-Pavao-#2]
@ramidedantas 

- [x] Instalar Git localmente
- [x] Criar projeto local
- [x] Criar repositório local e realizar commits
- [x] Subir alterações para o repositório remoto
- [ ] Fazer alterações no repositório da turma

**Comment by ramidedantas** [comment]
Ok, deixar aberto até finalização das prática de Git básico.
